FROM nginx:1.25-alpine
COPY ctk-repo/index.html /usr/share/nginx/html
COPY ctk-repo/style.css /usr/share/nginx/html
COPY ctk-repo/about.html /usr/share/nginx/html
COPY ctk-repo/contact.html /usr/share/nginx/html
EXPOSE 80
